services:
  streamlit:
    build:
      context: ./
      dockerfile: ./streamlit.dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.streamlit.loadbalancer.server.port=80
      - traefik.http.routers.streamlit-http.entrypoints=http
      - traefik.http.routers.streamlit-http.rule=Host(`streamlit.localhost`)
      - traefik.docker.network=traefik-public
      # https
      # - traefik.http.routers.streamlit-https.entrypoints=https
      # - traefik.http.routers.streamlit-https.rule=Host(`streamlit.localhost`)
      # - traefik.http.routers.streamlit-https.tls=true
      # - traefik.http.routers.streamlit-https.tls.certresolver=le
      # - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      # - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # - traefik.http.routers.streamlit-http.middlewares=https-redirect
      # - traefik.http.routers.streamlit-https.middlewares=admin-auth
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
